### ISSUE TITLE
cannot start database service built with `pgstac:v0.3.5` 

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/pgstac#59]
docker-compose.yml
```yml
  database:
    container_name: stac-db
    platform: linux/amd64
    image: ghcr.io/stac-utils/pgstac:v0.3.5
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500
```

`docker-compose up database` 
```
stac-db  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/pgstac.sql
stac-db  | BEGIN
stac-db  | psql:/docker-entrypoint-initdb.d/pgstac.sql:2: error: sql/001_core.sql: No such file or directory
```

cc @bitner
