### ISSUE TITLE
Posgres 13 `create_items` result in `UndefinedTableError`

### ISSUE THREAD

**Issue by thomafred** [stac-utils/pgstac#72]
Hi there!

We are using the [stac-fastapi](https://github.com/stac-utils/stac-fastapi) with the pgstac backend. The database was initially set up using `pypgstac migrate`

We are attempting to insert a test item:

```json
{
  "type": "Feature",
  "stac_version": "1.0.0",
  "id": "test_item",
  "properties": {
    "datetime": "1990-12-27T08:27:00Z"
  },
  "bbox": [-180, -90, 180, 90],
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "links": [
    {
      "rel": "root",
      "href": "http://stac.mydomain.com/",
      "type": "application/json",
      "title": "stac-fastapi"
    },
    {
      "rel": "collection",
      "href": "https://stac.mydomain.com/collections/test_collection",
      "type": "application/json"
    },
    {
      "rel": "parent",
      "href": "https://stac.mydomain.com/collections/test_collection",
      "type": "application/json"
    },
    {
      "rel": "self",
      "href": "https://stac.mydomain.com/collections/test_collection/items/test_item",
      "type": "application/json"
    }
  ],
  "assets": {},
  "stac_extensions": [],
  "collection": "test_collection"
}
```

However the API is returning the following error:

```
asyncpg.exceptions.UndefinedTableError: relation "items_p1990w52" does not exist
```

I figured this might be caused by Partman not being installed, so we amended the database:

```sql
create schema partman;
create extension pg_partman with schema partman;

create table partman.pgstac_items_template(
    like pgstac.items
);

create index on partman.pgstac_items_template (datetime asc);
create index on partman.pgstac_items_template (end_datetime asc);
create index on partman.pgstac_items_template using gist(geometry);

select partman.create_parent('pgstac.items', 'datetime', 'native', 'weekly',
                             p_template_table := 'partman.pgstac_items_template');
```

This unfortunately did not help.

Not sure what is going on here. Are anyone able to point us in the direction of a solution?

**Comment by thomafred** [comment]
A quick update: I have attempted to recreate the issue using the following `docker-compose.yml`

```yml
services:
  dev:
    container_name: pgstac-dev
    image: pgstac-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    depends_on:
      - database
    volumes:
      - ./:/opt/src
    environment:
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=database
      - PGDATABASE=postgis
  database:
    container_name: pgstac-db
    image: pgstac-db
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=0.0.0.0
      - PGDATABASE=postgis
    ports:
      - "5439:5432"
    volumes:
      - pgstac-pgdata:/var/lib/postgresql/data
      - ./:/opt/src

  app-pgstac:
    container_name: stac-fastapi-pgstac
    image: MYTENANT.azurecr.io/app-stac-fastapi:latest
    platform: linux/amd64
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
      - RELOAD=false
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
    ports:
      - "8081:8081"
    depends_on:
      - database
volumes:
  pgstac-pgdata:
```

The STAC FastAPI image is built using the following dockerfile

```dockerfile
FROM python:3.8-slim as base

RUN apt-get update
RUN apt-get install -y \
    build-essential \
    git

RUN pip install \
    uvicorn \
    stac-fastapi.api \
    stac-fastapi.types \
    stac-fastapi.extensions \
    stac-fastapi.pgstac

ARG APP_PORT=8081

ENV APP_HOST 0.0.0.0
ENV APP_PORT $APP_PORT
ENV RELOAD "false"
ENV ENVIRONMENT local
ENV POSTGRES_USER username
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DBNAME stac
ENV POSTGRES_HOST_READER database
ENV POSTGRES_HOST_WRITER database
ENV POSTGRES_PORT 5432
ENV WEB_CONCURRENCY 10
ENV VSI_CACHE "TRUE"
ENV GDAL_HTTP_MERGE_CONSECUTIVE_RANGES "YES"
ENV GDAL_DISABLE_READDIR_ON_OPEN "EMPTY DIR"
ENV DB_MIN_CONN_SIZE 1
ENV DB_MAX_CONN_SIZE 1

EXPOSE $APP_PORT

CMD ["python", "-m", "stac_fastapi.pgstac.app"]
```

In fact, this did not recreate the issue, instead everything worked as it should. It therefore seems there may be an issue with how our database is configured. Our initial suspect is Partman.

Side note: The initial item JSON was missing geometry. This is invalid. I have updated the issue with a correction.
